source 'http://rubygems.org'

gem 'rspec'
gem 'cinch', '~> 2.1.0'
gem 'cinch-test'
gem 'mechanize'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'dm-postgres-adapter'
gem 'httparty'
gem 'google-api-client'
gem 'trollop'
gem 'rufus-lua'
gem 'mkfifo'
gem 'thin'
gem 'sinatra'
gem 'nokogiri'
#gem 'mail'
gem 'twilio-ruby'
gem 'hipchat-api'
gem 'capistrano', '<3'
gem 'pdf-reader'
gem '3scale_client'
gem 'htmlentities'

gem 'simplecov'
gem 'minitest'
gem 'timecop'

gem 'cinch-forecast-io', github: 'onewheelskyward/cinch-forecast-io'
