source 'http://rubygems.org'

gem 'rspec'
gem 'cinch'
gem 'cinch-test'
gem 'mechanize'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'dm-postgres-adapter'
gem 'httparty'
gem 'google-api-client'
gem 'trollop'
gem 'rufus-lua'
gem 'mkfifo'
gem 'thin'
gem 'sinatra'
gem 'nokogiri'
#gem 'mail'
gem 'twilio-ruby'
gem 'hipchat-api'
gem 'capistrano', '<3'

gem 'simplecov'
gem 'minitest'

